# Generated by Django 4.0.8 on 2025-07-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duration',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
