# Generated by Django 4.0.8 on 2025-07-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_duration_question_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='duration',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Total duration for the assessment in minutes'),
        ),
    ]
