# Generated by Django 4.0.8 on 2025-07-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_activitylog_courseenrollment_department_document_and_more'),
        ('assessments', '0003_remove_assessment_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
