# Generated by Django 4.0.8 on 2025-07-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_activitylog_courseenrollment_department_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('image', 'Image')], max_length=20),
        ),
    ]
