# Generated by Django 4.0.8 on 2025-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_delete_program_remove_course_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
