# Generated by Django 4.0.8 on 2025-07-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='course_banner_images/'),
        ),
    ]
