# Generated by Django 4.0.8 on 2025-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_banner_images/'),
        ),
    ]
