# Generated by Django 4.0.8 on 2025-07-29 06:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0009_alter_course_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseallocation',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])]),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])]),
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('user', 'course')},
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='session',
        ),
    ]
