# Generated by Django 4.0.8 on 2025-07-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_activitylog_courseenrollment_department_document_and_more'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.department'),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.department'),
        ),
    ]
